### ISSUE TITLE
query_string: '$query_string

### ISSUE THREAD

**Issue by llnbe** [dream-mo/prom-elastic-alert#6]
query_string: '$query_string' #query_string查询语句  

查询语句是什么格式 query: "level:ERROR" 这种吗

**Comment by dream-mo** [comment]
> query_string: '$query_string' #query_string查询语句
> 
> 查询语句是什么格式 query: "level:ERROR" 这种吗

是的，Lucene查询语法即可

**Comment by llnbe** [comment]
es7查询不到数据，命中为0，看板查询是有数据的
